steps:
  - name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', 'soma']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/soma', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/soma']

images: ['gcr.io/$PROJECT_ID/soma:latest']
tags: ['cloud-builders-community']